version: 0.2

phases:
  install:
    runtime-versions:
       ruby: 2.7
    commands:
      - bundle install
  pre_build:
    commands:
      - bundle exec standardrb --fix
      - ruby tests/unit/*
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy