version: 0.2

env:
  variables:
    UrlExpiration: "3"
    MaxFileSize: "5"
    AppName: 'basic-ruby'

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - . ./extra-env.sh
      - bundle install
      - bundle exec standardrb
      - bundle exec rspec
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy