AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  basic-ruby

  Sample SAM Template for basic-ruby

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ShowFormFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user_form/
      Handler: show_form.UserForm::ShowForm.handler
      Runtime: ruby2.7
      Events:
        ShowForm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_form/
      Handler: process_form.UserForm::ProcessForm.handler
      Runtime: ruby2.7
      Events:
        ProcessForm:
          Type: Api
          Properties:
            Path: /hello
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ProcessFormBucket
      Environment:
        Variables:
          PROCESS_FORM_BUCKET: !Ref ProcessFormBucket
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
  ProcessFormBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: basic-ruby-process-form
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShowFormApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShowFormFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShowFormFunction.Arn
  ShowFormFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShowFormFunctionRole.Arn
  ProcessFormFunction:
    Description: "Function to process form submissions"
    Value: !GetAtt ProcessFormFunction.Arn
  ProcessFormBucket:
    Description: "S3 Bucket that stores form submissions"
    Value: !Ref ProcessFormBucket
