AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  basic-ruby

  Sample SAM Template for basic-ruby

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  MaxFileSize:
    Type: Number
    Description: The max size in MB of the file being uploaded
    Default: 5
    MaxValue: 25
    MinValue: 5
    ConstraintDescription: The max file size can only be between 5MB and 25MB
  UrlExpiration:
    Type: Number
    Default: 10
    Description: The  max length of time in minutes that the user has to upload or download a file
    MinValue: 1
    MaxValue: 20
    ConstraintDescription: The minimum expiration time for a link 1 minute. The maxium expiration time is 20 minutes.

Resources:
  ShowFormFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user_form/
      Handler: show_form.UserForm::ShowForm.handler
      Runtime: ruby2.7
      Events:
        ShowForm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ProcessFormBucket
      Environment:
        Variables:
          PROCESS_FORM_BUCKET: !Ref ProcessFormBucket
          MAX_FILE_SIZE: !Ref MaxFileSize
          URL_EXPIRATION: !Ref UrlExpiration
  ConfirmUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_form/
      Handler: confirm_upload.UserForm::ConfirmUpload.handler
      Runtime: ruby2.7
      Events:
        ConfirmUpload:
          Type: Api
          Properties:
            Path: /confirm
            Method: get
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ProcessFormBucket
      Environment:
        Variables:
          PROCESS_FORM_BUCKET: !Ref ProcessFormBucket
          URL_EXPIRATION: !Ref UrlExpiration
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
  ConvertImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image_processing
      Handler: create_thumbnails.ImageProcessing::CreateThumbnails.handler
      Runtime: ruby2.7
      Events:
        ImageUploaded:
          Type: S3
          Properties:
            Bucket: !Ref ProcessFormBucket
            Events: s3::ObjectCreated:*
      Timeout: 600
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref ThumbnailsBucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ThumbnailsBucket
  ProcessFormBucket:
    Type: AWS::S3::Bucket
  ThumbnailsBucket:
    Type: AWS::S3::Bucket
  ConvertImageFunctionCanReadProcessForm:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ConvertImageFunctionCanReadProcessForm
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "s3::GetObject"
            Resource:
              - !Sub "${ProcessFormBucket.Arn}/*"
      Roles:
        - !Ref ConvertImageFunctionRole


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShowFormApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShowFormFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShowFormFunction.Arn
  ShowFormFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShowFormFunctionRole.Arn
  ConfirmUploadFunction:
    Description: "Function to process form submissions"
    Value: !GetAtt ConfirmUploadFunction.Arn
  ProcessFormBucket:
    Description: "S3 Bucket that stores form submissions"
    Value: !Ref ProcessFormBucket
